steps:
- name: node:20.15.0-slim
  entrypoint: sh
  dir: /workspace
  args:
    - -c
    - ./deploy-prod.sh $$NPM_TOKEN
  secretEnv: ['NPM_TOKEN']
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  dir: /workspace
  args:
    - -c
    - |
      cd lib && grep version package.json | cut -c15-20 | gcloud secrets versions add ui-version --data-file=-
      echo "0" | gcloud secrets versions add ui-version-alpha --data-file=-
availableSecrets:
  secretManager:
    - versionName: projects/18279890124/secrets/npm-access-key/versions/latest
      env: 'NPM_TOKEN'
