steps:
  - name: 'node:22'
    entrypoint: 'npm'
    id: Install CLI
    args: ['install', '-g', '@angular/cli']
  - name: 'node:22'
    entrypoint: 'npm'
    id: Install Dependencies
    args: ['ci']
  - name: 'node:22'
    entrypoint: 'npm'
    id: Build Library
    args: ['run', 'build:ui:prod']
  - name: 'node:22'
    id: Publish to NPM
    secretEnv: ['NPM_TOKEN']
    entrypoint: bash
    args:
      - -c
      - |
        npm config set -- '//registry.npmjs.org/:_authToken' "$$NPM_TOKEN"
        cd dist/@lab900/ui
        npm publish --ignore-scripts
availableSecrets:
  secretManager:
    - versionName: projects/18279890124/secrets/npm-access-key/versions/latest
      env: 'NPM_TOKEN'
timeout: "900s"
