steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    dir: /workspace
    args:
      - -c
      - |
        cd lib && grep version package.json | cut -c15-20 | gcloud secrets versions add ui-version --data-file=-
        expr $$UI_VERSION_ALPHA + 1 | gcloud secrets versions add ui-version-alpha --data-file=-
        expr $$UI_VERSION_ALPHA + 1 > /workspace/ui_version_alpha.txt
    secretEnv: ['UI_VERSION_ALPHA']
  - name: node:16.13.1-slim
    entrypoint: sh
    dir: /workspace
    args:
      - -c
      - ./deploy-dev.sh $$NPM_TOKEN $$UI_VERSION $(cat ui_version_alpha.txt)
    secretEnv: ['NPM_TOKEN', 'UI_VERSION']
availableSecrets:
  secretManager:
    - versionName: projects/18279890124/secrets/npm-access-key/versions/latest
      env: 'NPM_TOKEN'
    - versionName: projects/18279890124/secrets/ui-version/versions/latest
      env: 'UI_VERSION'
    - versionName: projects/18279890124/secrets/ui-version-alpha/versions/latest
      env: 'UI_VERSION_ALPHA'
